version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    tty: true
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - .:/var/www/html

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
